Added Inspired by Things themes
Zettelkasten-Method/The-Archive-Themes pull request #15
Opened 2022-11-16 22:09 UTC by mattstratford

A dark theme and a light scheme borrowing colour palette from a popular to-do list manager. 

Light version
<img width="1280" alt="Screenshot of Inspired by Things theme light mode" src="https://user-images.githubusercontent.com/3720894/202305006-3077fdbc-de3d-4ee9-ae52-8dfa1a6332c3.png">

Dark version
<img width="1280" alt="Screenshot of Inspired by Things theme dark mode" src="https://user-images.githubusercontent.com/3720894/202305078-980f11a8-630b-43fd-b5dd-a73721f0c0f0.png">

2022-11-21 09:50 UTC, DivineDominion requested changes
Thanks for updating your theme! Just one issue with the font-family setting -- these currently wouldn't load any font AFAIK --, then I'll merge. Please ping me in your reply to ensure I get a notification :)

2022-11-21 09:50 UTC, DivineDominion commented on Themes/Inspired by Things (Dark).theme.json
> +            "font-family":"iA Writer Mono S, Courier, sans-serif",
Font families don't have fallbacks as they have with CSS, so you can just pick the iA Writer ones and omit the rest (also for the font families of the light variant)

2022-11-21 12:44 UTC, mattstratford reviewed
@DivineDominion Made the changes as requested, you can approve (or suggest other changes). P.S. I am very unfamiliar with coding/Github so I hope I am doing this right :)

2022-11-26 09:44 UTC, DivineDominion approved these changes
Looks good to me, thanks 👍

2022-11-26 09:45 UTC, merged