Adding Catppuccin Flavors (Themes)
Zettelkasten-Method/The-Archive-Themes pull request #19
Opened 2024-08-29 20:46 UTC by rogeruiz

Hi. I'd like to get these four themes into the official themes archive for _The Archive_. To learn more about Catppuccin, [view their website here](https://catppuccin.com).

2024-09-01 22:09 UTC, rogeruiz commented
Hey @DivineDominion is there any chance this could be reviewed and merged in soon? I've gotten approval from the Catppuccin organization. I can include screenshots as well. But they're accessible at catppuccin/catppuccin#2519 in the description and the repository called `the-archive` in the Catppuccin organization.

Thank you!

2024-09-01 23:15 UTC, sgoudham commented on Themes/catppuccin-frappe.theme.json
> +      "basedOn": "https://github.com/catppuccin/catppuccin"
I think it'd be nice to link to the repository itself.

```suggestion
      "basedOn": "https://github.com/catppuccin/the-archive"
```

2024-09-02 06:11 UTC, DivineDominion requested changes
Thank you! Looks great.

Could you copy the `catppuccin/the-archive` repo's screenshot to your original PR comment at the top? We're not currently displaying screenshots in the app, but want to :)

2024-09-02 06:11 UTC, DivineDominion commented on Themes/catppuccin-frappe.theme.json
> +  ],
Maybe add another JSON object here to link to the original Catppuccin repo or mention the original author(s) instead? As far as I'm concerned, your name on top as the author of this file, then something to acknowledge the community behind it?

```suggestion
  "author": [
    {
      "name": "Roger Steve Ruiz",
      "url": "https://rog.gr/"
    },
    {
      "name": "Catppuccin Organization",
      "url": "https://github.com/catppuccin/the-archive"
    }
  ],
```

Something like that would be parseable and visible in the app; the "basedOn" key would not be a.t.m. and just be flavor for readers of this code :)

2024-09-02 06:11 UTC, DivineDominion commented on Themes/catppuccin-latte.theme.json
> +  ],
(Same here; slight inconsistency with URLs right now)

2024-09-02 06:16 UTC, DivineDominion commented on Themes/catppuccin-macchiato.theme.json
> +  ],
(Same as above, author/URL inconsistency)

2024-09-02 06:16 UTC, DivineDominion commented on Themes/catppuccin-mocha.theme.json
> +  ],
(Same as above, author/URL inconsistency)

2024-09-02 12:40 UTC, julve commented
No problem incorporating this instead of mine @DivineDominion. Thanks @rogeruiz!

2024-09-03 06:25 UTC, DivineDominion approved these changes
Thank you, that's great!

2024-09-03 06:26 UTC, merged